name: Terraform PR Workflow

on:
    push:

jobs:
  TF_lint:
      runs-on: ubuntu-latest
      #runs-on: ${{ matrix.os }}

      #strategy:
      #  matrix:
      #    os: [ubuntu-latest, macos-latest, windows-latest]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup TFLint
          uses: terraform-linters/setup-tflint@v4
          with:
            tflint_wrapper: false
            tflint_version: latest

        - name: Run TFLint
          id: tflint
          run: tflint --recursive -f compact
        
        - run: echo ${{ steps.tflint.outputs.stdout }}
        - run: echo ${{ steps.tflint.outputs.stderr }}
        - run: echo ${{ steps.tflint.outputs.exitcode }}